### ISSUE TITLE
Cloned this to run locally but getting bunch of errors

### ISSUE THREAD

**Issue by andyfensham** [NetCoreApps/FileBlazor#1]
I cloned this repository sample to run locally but trying to compile it I get a bunch of errors.

![Snag_144c0d83](https://user-images.githubusercontent.com/5065306/199882197-d95759fe-f88a-4586-896e-1f5801ab5ce6.png)

**Comment by Layoric** [comment]
Thanks for reporting @andyfensham , I've updated the project to match our updated templates and can confirm I can run locally without issue. Let us know if you have any other problems. 👍
