### ISSUE TITLE
When I try to run the application, I am getting error

### ISSUE THREAD

**Issue by ganeshan** [NetCoreApps/FileBlazor#2]
I am using Rider on Intel Mac
Unhandled exception. System.AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: FileBlazor.ServiceInterface.EmailServices Lifetime: Transient ImplementationType: FileBlazor.ServiceInterface.EmailServices': Unable to resolve service for type 'FileBlazor.ServiceInterface.SmtpConfig' while attempting to activate 'FileBlazor.ServiceInterface.EmailServices'.)
Also, I needed to change:
`services.AddSingleton<ICrudEvents>(c =>
                new OrmLiteCrudEvents(c.Resolve<IDbConnectionFactory>()));`
to
` services.AddSingleton<ICrudEvents>(c =>
                new OrmLiteCrudEvents(c.GetRequiredService<IDbConnectionFactory>()));`

**Comment by ganeshan** [comment]
The complete output from `dotnet run` is:
Building...
/Users/thisuser/github/FileBlazor/FileBlazor/Configure.Auth.cs(16,17): warning CS0618: 'IdentityAuthContext<AppUser, int>.EnableCredentialsAuth' is obsolete: 'Use CredentialsAuth()' [/Users/thisuser/github/FileBlazor/FileBlazor/FileBlazor.csproj]
/Users/thisuser/github/FileBlazor/FileBlazor/Components/Account/Pages/AccessDenied.razor(15,31): warning CS8618: Non-nullable property 'ReturnUrl' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. [/Users/thisuser/github/FileBlazor/FileBlazor/FileBlazor.csproj]
/Users/thisuser/github/FileBlazor/FileBlazor/Configure.Db.cs(30,45): warning CS8602: Dereference of a possibly null reference. [/Users/thisuser/github/FileBlazor/FileBlazor/FileBlazor.csproj]
/Users/thisuser/github/FileBlazor/FileBlazor/Configure.Db.cs(31,55): warning CS8602: Dereference of a possibly null reference. [/Users/thisuser/github/FileBlazor/FileBlazor/FileBlazor.csproj]
/Users/thisuser/github/FileBlazor/FileBlazor/Configure.Db.cs(32,53): warning CS8602: Dereference of a possibly null reference. [/Users/thisuser/github/FileBlazor/FileBlazor/FileBlazor.csproj]
/Users/thisuser/github/FileBlazor/FileBlazor/Configure.Markdown.cs(56,19): warning CS8618: Non-nullable property 'LocalBaseUrl' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. [/Users/thisuser/github/FileBlazor/FileBlazor/FileBlazor.csproj]
/Users/thisuser/github/FileBlazor/FileBlazor/Configure.Markdown.cs(57,19): warning CS8618: Non-nullable property 'PublicBaseUrl' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. [/Users/thisuser/github/FileBlazor/FileBlazor/FileBlazor.csproj]
/Users/thisuser/github/FileBlazor/FileBlazor/MarkdownPagesBase.cs(139,20): warning CS8604: Possible null reference argument for parameter 'newDoc' in 'void MarkdownFileBase.Update(MarkdownFileBase newDoc)'. [/Users/thisuser/github/FileBlazor/FileBlazor/FileBlazor.csproj]
/Users/thisuser/github/FileBlazor/FileBlazor/MarkdownPagesBase.cs(731,19): warning CS8618: Non-nullable property 'Text' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. [/Users/thisuser/github/FileBlazor/FileBlazor/FileBlazor.csproj]
/Users/thisuser/github/FileBlazor/FileBlazor/MarkdownPagesBase.cs(732,19): warning CS8618: Non-nullable property 'Link' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. [/Users/thisuser/github/FileBlazor/FileBlazor/FileBlazor.csproj]
/usr/local/share/dotnet/sdk/8.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(284,5): warning NETSDK1206: Found version-specific or distribution-specific runtime identifier(s): centos7-x64. Affected libraries: Microsoft.CognitiveServices.Speech. In .NET 8.0 and higher, assets for version-specific and distribution-specific runtime identifiers will not be found by default. See https://aka.ms/dotnet/rid-usage for details. [/Users/thisuser/github/FileBlazor/FileBlazor/FileBlazor.csproj]
Unhandled exception. System.AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: FileBlazor.ServiceInterface.EmailServices Lifetime: Transient ImplementationType: FileBlazor.ServiceInterface.EmailServices': Unable to resolve service for type 'FileBlazor.ServiceInterface.SmtpConfig' while attempting to activate 'FileBlazor.ServiceInterface.EmailServices'.)
 ---> System.InvalidOperationException: Error while validating the service descriptor 'ServiceType: FileBlazor.ServiceInterface.EmailServices Lifetime: Transient ImplementationType: FileBlazor.ServiceInterface.EmailServices': Unable to resolve service for type 'FileBlazor.ServiceInterface.SmtpConfig' while attempting to activate 'FileBlazor.ServiceInterface.EmailServices'.
 ---> System.InvalidOperationException: Unable to resolve service for type 'FileBlazor.ServiceInterface.SmtpConfig' while attempting to activate 'FileBlazor.ServiceInterface.EmailServices'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(ServiceIdentifier serviceIdentifier, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, ServiceIdentifier serviceIdentifier, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceDescriptor serviceDescriptor, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ValidateService(ServiceDescriptor descriptor)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ValidateService(ServiceDescriptor descriptor)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(ICollection`1 serviceDescriptors, ServiceProviderOptions options)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(ICollection`1 serviceDescriptors, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.Hosting.HostApplicationBuilder.Build()
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder.Build()
   at Program.<Main>$(String[] args) in /Users/thisuser/github/FileBlazor/FileBlazor/Program.cs:line 79

**Comment by mythz** [comment]
Should now build after https://github.com/NetCoreApps/FileBlazor/commit/7d6e79f19331cab1a64deeaca1f8e320e2c9c4f8

**Comment by ganeshan** [comment]
Hello @mythz , 
The build succeeds. But when I run the code, it fails with the error I mentioned above. Sorry, I was not clear in defining my scenario. The Build issue is fixed by your commit and the run still fails. Even though the email is configured to be `IdentityNoOpEmailSender`, the error is thrown, I am not sure why.

**Comment by mythz** [comment]
Yeah we need to uncomment the EmailService inheriting from `Service` unless SmtpConfig is configured:

https://github.com/NetCoreApps/FileBlazor/commit/0a8766d69e05a2f1ca6f7a2f6acaccbde9b874d7

I've also cleaned up some other code to reduce some warnings, latest version should run after running `npm run migrate` to create the app database.
